language: csharp
mono: none
solution: NapierBankMessaging.sln
install:
  - dotnet restore

script:
  - donet build
  - dotnet test NapierBankMessagingTest/NapierBankMessagingTest.csproj

after_success:
  - bash <(curl -s https://codecov.io/bash)